[[pages]]
path = "pages/homePage.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "pages/profilePage.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "pages/importPage.py"
name = "Import Data"
icon = "ğŸ“¥"

[[pages]]
path = "pages/trainingPage.py"
name = "Training"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/evaluatePage.py"
name = "Evaluation"
icon = "ğŸ“Š"
