[[pages]]
path = "pages/homePage.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "pages/profilePage.py"
name = "Profile"
icon = "ğŸ§‘â€ğŸ’¼"

[[pages]]
path = "pages/trainingPage.py"
name = "Training"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/evaluatePage.py"
name = "Evaluation"
icon = "ğŸ“Š"
