[[pages]]
path = "pages/homePage.py"
name = "Home Page"
icon = "ğŸ "

[[pages]]
path = "pages/profilePage.py"
name = "Profile Page"
icon = "âš™ï¸"

[[pages]]
path = "pages/importPage.py"
name = "Import Page"
icon = "ğŸ“‚"

[[pages]]
path = "pages/trainingPage.py"
name = "Training Page"
icon = "ğŸ“Š"
